"""
Ctrl-Z FRC Team 4096
FIRST Robotics Competition 2020-2021
Code for robot "Krono-Z"
contact@team4096.org
"""

import math

"""
Prepend these to any IDs.
DIO = Digital I/O
AIN = Analog Input
PWM = Pulse Width Modulation
CAN = Controller Area Network
PCM = Pneumatic Control Module
PDP = Power Distribution Panel
"""

### CONSTANTS ###

## DRIVETRAIN ##

# MOTORS#

CAN_DRIVE_MOTOR_RIGHT_1 = 3 # DT3
CAN_DRIVE_MOTOR_RIGHT_2 = 4 # DT4
CAN_DRIVE_MOTOR_RIGHT_3 = 5 # DT5
CAN_DRIVE_MOTOR_LEFT_1 = 0 # DT0
CAN_DRIVE_MOTOR_LEFT_2 = 1 # DT1
CAN_DRIVE_MOTOR_LEFT_3 = 2 # DT2

CAN_SHOOTER_0 = 6 # SH0
CAN_SHOOTER_1 = 7 # SH1

CAN_TURRET = 8 # TR0

CAN_CLIMBER_0 = 9 # CL0
CAN_CLIMBER_1 = 10 # CL1


CAN_INTAKE = 11 # IT0

CAN_INDEXER_LEFT = 12 # IX2
CAN_INDEXER_RIGHT = 13 # IX1
CAN_INDEXER_BOTTOM = 14 # IX0

# ENCODERS - grayhill encoders #
DIO_DRIVE_ENC_LEFT_1					= 0
DIO_DRIVE_ENC_LEFT_2					= 1
DIO_DRIVE_ENC_RIGHT_1					= 2
DIO_DRIVE_ENC_RIGHT_2					= 3

DIO_CLIMBER_TOP_LIMIT					= 4
DIO_CLIMBER_BOTTOM_LIMIT				= 5

DRIVE_ENCODER_LEFT_REVERSED				= False
DRIVE_ENCODER_RIGHT_REVERSED			= True

DRIVE_CORRECTION_ENABLED				= False

# DRIVE_WHEEL_DIAMETER_INCHES				= 6
# DRIVE_ENCODER_TICKS_PER_REV				= 256
# DRIVE_TICKS_PER_FOOT					= 12 / (math.pi * DRIVE_WHEEL_DIAMETER_INCHES / DRIVE_ENCODER_TICKS_PER_REV)
#DRIVE_TICKS_PER_FOOT					= 914.25	# just measured this on floor
DRIVE_TICKS_PER_METER_LEFT  			= 16537/4
DRIVE_TICKS_PER_METER_RIGHT				= 16537/4

# Values from last year... might need to be changed
DRIVE_CORRECTION_ROTATION_THRESHOLD		= 0.05
DRIVE_CORRECTION_PROPORTION_FORWARD		= 0.1
DRIVE_CORRECTION_PROPORTION_REVERSE		= 0.04
DRIVE_CORRECTION_PROPORTION_FORWARD_ENC	= 0.009
DRIVE_CORRECTION_PROPORTION_REVERSE_ENC	= 0.009

DRIVE_ROTATION_MULTIPLIER 				= 0.85

## TURRET ##


## LIMELIGHT ##
LIMELIGHT_DRIVER_CAMERA_MODE_ENABLED	= 1
LIMELIGHT_DRIVER_CAMERA_MODE_DISABLED	= 0
LIMELIGHT_DRIVER_CAMERA_MODE_DEFAULT	= LIMELIGHT_DRIVER_CAMERA_MODE_DISABLED
LIMELIGHT_STREAM_MODE					= 2		# 0 = side-by-side, 1 = PIP Main, 2 = PIP Secondary
LIMELIGHT_MOUNT_ANGLE					= math.radians(25)	# 25 degrees above horizontal
LIMELIGHT_MOUNT_HEIGHT					= 24.0	# in inches

OUTER_PORT_TARGET_WIDTH					= 39.0
OUTER_PORT_TARGET_HEIGHT				= 17.0
OUTER_PORT_TARGET_DISTANCE_FROM_GROUND	= 88.5		# Distance from ground to center of hex target
LIMELIGHT_DISTANCE_FUDGE_INCHES			= -10.0		# Inches to add to final distance calculation

LIMELIGHT_LED_MODE_PIPELINE				= 0		# Use LED mode set in current pipeline
LIMELIGHT_LED_MODE_OFF					= 1		# off
LIMELIGHT_LED_MODE_BLINK				= 2		# blink
LIMELIGHT_LED_MODE_ON					= 3		# on

### PNEUMATICS ###

CAN_PCM								    = 0

PCM_SOLENOID_CLIMBER_BRAKE_1			= 4
PCM_SOLENOID_CLIMBER_BRAKE_2			= 5

PCM_SOLENOID_CLIMBER_DEPLOY_1			= 2
PCM_SOLENOID_CLIMBER_DEPLOY_2			= 3
PCM_SOLENOID_INTAKE_DEPLOY_1            = 0
PCM_SOLENOID_INTAKE_DEPLOY_2            = 1

AIN_PRESSURE_SENSOR 					= 0

### SHOOTER PID ###

SHOOTER_MAX_VELOCITY = 93_000 # unit = ticks per 100ms ?

SHOOTER_KF = 1023 / SHOOTER_MAX_VELOCITY
SHOOTER_KP = .05 # .02
SHOOTER_KI = 0	# was 0.0001
SHOOTER_KD = 0		# 4	# was 10, 15 is better, zero best
SHOOTER_IZ = 0 # 4000

### HOOD ###
'''
If set A doesn't work well, try set B. They generate similar hood angles but set B shoots flatter shots possibly resulting in shots missed low
'''

# In inches
HOOD_MIN_DISTANCE = 55
HOOD_MAX_DISTANCE = 240

HOOD_MIN_DISTANCE_ANGLE = 43.4
HOOD_MAX_DISTANCE_ANGLE = 20

# SET A
HOOD_A = 0.00130755
HOOD_B = -0.511557 
HOOD_C = 67.5568

# SET B
# HOOD_A = 0.00105557
# HOOD_B = -0.447931
# HOOD_C = 63.9199

### NOT USED ###

# Minimum power required to move
# Minimum power required.
DRIVE_MIN_ROTATION_OUTPUT_TANK			= 0.55
DRIVE_MIN_OUTPUT_TANK 					= 0.5


### OTHER ###
MAX_ACCEL								= 0.981
LEDS_ENABLED							= True



CAN_PDP									= 0


# trajectory stuff
KS_VOLTS = 1.6142

KV_VOLT_SECONDS_PER_METER = 2.3644

KA_VOLT_SECONDS_SQUARED_PER_METER = 0.077949

# KP_DRIVE_VEL = 1.3812
KP_DRIVE_VEL = 1.3812 * 1.5
TRACK_WIDTH = 0.75438

# USER DEFINED - below
MAX_SPEED_METERS_PER_SECOND = 4.4
MAX_ACCELERATION_METERS_PER_SECOND_SQUARED = 3.2
RAMSETE_B = 2
RAMSETE_ZETA = 0.7

TURRET_MIN_ROTATION_OUTPUT = 0